

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abril
 */
public class ActualizacionHistorial extends javax.swing.JFrame {
    String rfc_Medico;

    TDA_Expedientes te= new TDA_Expedientes();
    public ActualizacionHistorial() {
        initComponents();
        this.setSize(1000, 641);
    }

    public void setRFCMed(String rfc){
        rfc_Medico=rfc;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDiag = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFarmaco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtHist = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPronostico = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtPresentacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Diagnostico");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 110, 82, 17);

        txtDiag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagActionPerformed(evt);
            }
        });
        getContentPane().add(txtDiag);
        txtDiag.setBounds(70, 140, 287, 49);

        jLabel2.setText("Observaciones");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 210, 103, 17);

        txtObs.setColumns(20);
        txtObs.setRows(5);
        txtObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObsKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtObs);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 240, 560, 190);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono-SIH-ISSSTEico1_phixr1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(780, 10, 186, 200);

        jLabel4.setText("Farmaco Recomendado");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 480, 190, 17);
        getContentPane().add(txtFarmaco);
        txtFarmaco.setBounds(90, 510, 210, 40);

        jLabel5.setText("Indicaciones");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(640, 220, 140, 17);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1460672739_floppy_disk_save.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 590, 110, 36);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1459970446_button_cancel.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 590, 130, 40);

        jLabel6.setText("Historial");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 70, 70, 17);
        getContentPane().add(txtHist);
        txtHist.setBounds(400, 70, 210, 27);

        jLabel7.setText("RFC");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 60, 26, 17);
        getContentPane().add(txtRFC);
        txtRFC.setBounds(120, 70, 150, 27);

        jButton3.setText("Consultar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(410, 140, 80, 29);

        txtPronostico.setColumns(20);
        txtPronostico.setRows(5);
        txtPronostico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPronosticoKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtPronostico);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(640, 260, 262, 87);

        jLabel8.setText("Presentacion del Farmaco");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 470, 200, 17);
        getContentPane().add(txtPresentacion);
        txtPresentacion.setBounds(370, 510, 190, 40);

        jLabel9.setText("Nombre");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 20, 150, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 20, 140, 27);

        jLabel11.setText("Apellido");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(320, 20, 57, 17);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(410, 10, 200, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TDA_Expedientes te=new TDA_Expedientes();
        String valor=txtRFC.getText();
//te.historialReciente(txtRFC.getText());
        if(txtRFC.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "El campo RFC se encuentra vacío, por favor llenelo");
        }else{
            te.setRFCD(valor);
            int historial= te.historialReciente(valor);
        if(historial!=0){
              txtHist.setText(""+historial);
        }else{
                showMessageDialog(null,"No encontrado");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private void txtObsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObsKeyTyped
           txtObs.setLineWrap(true);
// Para que haga el salto de línea buscando espacios entre las palabras
           txtObs.setWrapStyleWord(true);
    }//GEN-LAST:event_txtObsKeyTyped

    private void txtPronosticoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPronosticoKeyTyped
        txtPronostico.setLineWrap(true);
// Para que haga el salto de línea buscando espacios entre las palabras
           txtPronostico.setWrapStyleWord(true);
    }//GEN-LAST:event_txtPronosticoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String diagnostico= txtDiag.getText(); 
         String observaciones= txtObs.getText(); 
         String pronostico= txtPronostico.getText(); 
         String farmaco = txtFarmaco.getText();
         int historial=Integer.parseInt(txtHist.getText());
        
        Connection miCon = (new Conexion_BD()).conexion();
        if(miCon!=null){
            try{
               Statement stmt = miCon.createStatement();
               String sql = "Update HistorialClinico set PadecActual_HistorialClinico='"+diagnostico+"', Diagnostico_HistorialClinico ='"+
                       observaciones+"', Farmacol_HistorialClinico = '"+farmaco+"', Pronosticos_HistorialClinico = '"+pronostico+"' where  id_HistorialClinico = '"+
                       historial+"';";
              stmt.executeUpdate(sql);
              miCon.close();
                JOptionPane.showMessageDialog(this, "Actualizado con exito");
            }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);              
//JOptionPane.showMessageDialog(null, "No es posible realizar el movimiento");
    }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtDiagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizacionHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizacionHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizacionHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizacionHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizacionHistorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtDiag;
    private javax.swing.JTextField txtFarmaco;
    private javax.swing.JTextField txtHist;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextField txtPresentacion;
    private javax.swing.JTextArea txtPronostico;
    private javax.swing.JTextField txtRFC;
    // End of variables declaration//GEN-END:variables
}
