/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abril
 */
public class CambiarContra extends javax.swing.JFrame {
      String rfc;
    /**
     * Creates new form Informacion
     */
    public CambiarContra() {
        initComponents();
        this.setTitle("Cambio de Contraseña");
        //txtNewPass.setSize(60, 3);
        //txtNewPass.setText("        ");
        //txtRNewPass.setSize(60,3);
        //txtRNewPass.setText("       ");
         this.setSize(482, 402);
         txtRFC.setEditable(false);
    }

    public void setUsuario(String rfc){
        this.rfc=rfc;
        txtRFC.setText(rfc);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNewPass = new javax.swing.JPasswordField();
        txtRNewPass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/banner.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 12, 420, 70);

        jLabel2.setText("RFC ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 92, 64, 32);
        getContentPane().add(txtRFC);
        txtRFC.setBounds(210, 95, 140, 27);

        jLabel3.setText("Nueva Contraseña");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 150, 128, 17);

        jLabel4.setText("Repetir nueva contraseña");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(12, 228, 177, 17);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1460672739_floppy_disk_save.png"))); // NOI18N
        jButton1.setText("Cambiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(232, 334, 110, 40);
        getContentPane().add(txtNewPass);
        txtNewPass.setBounds(210, 180, 140, 27);
        getContentPane().add(txtRNewPass);
        txtRNewPass.setBounds(210, 270, 140, 27);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono-SIH-ISSSTEico1_phixr1.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 100, 200, 220);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whynot.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 490, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AccesoLogin  al=new AccesoLogin();
        
        char[] arrayC = txtNewPass.getPassword();
        String pass = new String(arrayC);
        char[] newC = txtRNewPass.getPassword();
        String passrep= new String (newC);
        
        if(pass.equals(passrep)){
            al.setPass(passrep);
            al.setUsuario(txtRFC.getText());
             al.cambiarContra();
        }
        al.conectar();
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarContra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarContra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JPasswordField txtRNewPass;
    // End of variables declaration//GEN-END:variables
}
