
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abril
 */
public class ConsultaExpedientes extends javax.swing.JFrame {
  DefaultTableModel model;
    /**
     * Creates new form ConsultaExpedientes
     */
    public ConsultaExpedientes() {
        initComponents();
        model= (DefaultTableModel)tblExp.getModel();
        tblExp.setEnabled(false);
        this.setSize(1004, 594);
        
    }

    protected void tabla(){
       TDA_Expedientes a= new TDA_Expedientes();
        Clear_Table();
        a.setRfc(txtRFC.getText());
        a.getDatos(model);
        
        tblExp.setEnabled(false);
   }
    
    public void Clear_Table(){
    
        for(int i=0;i<tblExp.getRowCount();i++){
            model.removeRow(i);
            i-=1;
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNumExp = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExp = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono-SIH-ISSSTEico1_phixr1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(700, 10, 186, 200);

        jLabel2.setText("Consulta de Expedientes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 280, 17);

        jLabel3.setText("RFC");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 50, 26, 17);

        txtRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRFCActionPerformed(evt);
            }
        });
        getContentPane().add(txtRFC);
        txtRFC.setBounds(130, 50, 190, 27);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1463384354_search.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(300, 100, 140, 44);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1462963676_arrow-back.png"))); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(790, 550, 130, 44);

        jLabel10.setText("Expediente");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(360, 50, 90, 17);
        getContentPane().add(txtNumExp);
        txtNumExp.setBounds(470, 50, 140, 27);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 180, 660, 6);

        tblExp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Expediente", "Presion", "Temperatura", "Frecuencia Card", "Frecuencia Respiratoria", "Perimetro abdominal", "Diagnostico", "Pronostico"
            }
        ));
        jScrollPane1.setViewportView(tblExp);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 930, 310);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whynot.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
       if(txtRFC.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "El campo RFC se encuentra vacío, por favor llenelo");
        }else{
        TDA_Expedientes te=new TDA_Expedientes(txtRFC.getText());
        if(te.numExpediente()){
            txtNumExp.setText(te.getNumExp());
            tabla();
            //JOptionPane.showMessageDialog(this, "Correctamente realizado");
        }else{
                showMessageDialog(null,"No encontrado");
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    /*select h.id_ExpedienteClinico, e.RFC_Derechoh, h.Presion_Historial, Temp_HistorialClinico, e.TiSang_ExpedienteClinico, FCardiaca_HistorialClinico, FRespiratoria_HistorialClinico, PerAbdominal_HistorialClinico from HistorialClinico h 
    inner join ExpedienteClinico e on h.id_ExpedienteClinico = e.id_ExpedienteClinico where RFC_Derechoh= 'LOHP840505AA0' */
    private void txtRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaExpedientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblExp;
    private javax.swing.JTextField txtNumExp;
    private javax.swing.JTextField txtRFC;
    // End of variables declaration//GEN-END:variables
}
